### PR TITLE
Streamilned Paint menu for wheel color and pearl selection

### PR DESCRIPTION
**Pull request by TSM4278**
No longer forces you to choose paint type unnecessarily.

### CODE REVIEW

**Comment by gtav-ent** [comment]
Looks good, and just in time for release :)

**Comment by TSM4278** [comment]
Yeah, I saw you were prepping for a release so I rushed to throw something together.

**Comment by TSM4278** [comment]
Actually, I'm not sure if this was intentional but this doesn't seem to be included in the current compiled release.

**Comment by gtav-ent** [comment]
How about now? Possibly made a mistake there,

**Comment by TSM4278** [comment]
Yup, now it's there.

**Comment by gtav-ent** [comment]
Thanks for testing that. I also found another bug relating to NPC models, so I'll be updating again in a minute.

**Pull request merged**
