### PR TITLE
Refactor set_status_text to use the notifications

### PR DESCRIPTION
**Pull request by qaisjp**

### CODE REVIEW

**Comment by qaisjp** [comment]
Timeouts don't work yet, will update pull request later.

**Comment by qaisjp** [comment]
Bump. I have been unable to find the right native for a notification timeout, but the existing code doesn't use timeouts anyway so hopefully it shouldn't be an issue.

**Comment by gtav-ent** [comment]
I haven't looked at this at all yet, but I suspect not all uses of what was the basic text overlay are directly replaceable, so this will take a bit of time to sort out.

**Comment by qaisjp** [comment]
Okay, I'll take a look at all the uses tomorrow and get back to you on where text overlay is used.

**Comment by qaisjp** [comment]
Updated to resolve merge conflicts.

**Comment by gtav-ent** [comment]
Merged. I kept the old version too because it has its uses (mostly testing, but also the XYZ coord output)

**Pull request merged**
