### PR TITLE
Rename "wrap in vehicle" to "spawn into vehicle"

### PR DESCRIPTION
**Pull request by qaisjp**
Was originally for naming to "warp into vehicle"

### CODE REVIEW

**Comment by qaisjp** [comment]
bump

**Comment by fvqu** [comment]
"Spawn in Vehicle" would probably be easiest to understand

**Comment by gtav-ent** [comment]
I saw this and wasn't sure. "Wrap in vehicle" kind of fitted to me, and "warp in" less so, although I definitely see what you mean. Any more ideas?

**Comment by qaisjp** [comment]
Oh, I always assumed "wrap" was a typo, by fvqu has come up with the most
self explanatory name "spawn into vehicle"

**Comment by qaisjp** [comment]
Okay, updated the commit to what @fvqu suggested

**Comment by qaisjp** [comment]
Updated the pull request to reflect the latest changes.

**Pull request merged**
