### PR TITLE
Add vehicle creation support for FiveM

### PR DESCRIPTION
**Pull request by qaisjp**

### CODE REVIEW

**Comment by gtav-ent** [comment]
What does this argument do?

**Comment by qaisjp** [comment]
Allows you spawn the vehicle online.

(No need to worry about cheaters, because the official script hook is disabled online anyway. If they can go through the trouble of getting a patched scripthook that works online, they'll probably find a way to get their trainer to spawn online as well. Plus, vehicle spawning is much less than an issue of what this trainer can do if exposed online. Trainers are permitted in FiveM.)

**Comment by dratom** [comment]
Thank You qaisjp for confusing me enough that I had to google FiveM. 
I am now very excited at the prospect of building mods catered to user created game modes.

**Comment by qaisjp** [comment]
Thank you for merging this commit.

**Pull request merged**
