### PR TITLE
Airbrake Function, Wanted Level Freeze, Weather Freeze and Never Wanted shortcut

### PR DESCRIPTION
**Pull request by sondaismith**
-Added an Airbrake function which allows you to freely move the player around the world. Activated using the F6 key.
-The "Wanted Level" option under the Player menu now freezes the police response level.
-The "Never Wanted" option now has a hotkey - "]". Overrides frozen police level, but does not disable it.
-The weather can be frozen at selected options using the "Freeze Weather" option under the Weather menu.
-The player model can be made invisible using the "Invisibility" option displayed under the Player menu.

### CODE REVIEW

**Comment by gtav-ent** [comment]
I will get around to this but it's a bit of a mega-merge, won't process automatically, and so is going to take some time to sort out.

**Comment by Mysterius** [comment]
I compiled it myself and tested it. It seems there's a small bug : when you have the "freeze weather" option activated and try to change weather without first deactivating it, the game crashes.

**Comment by sondaismith** [comment]
OK, I'll try fixing that issue.

**Comment by gtav-ent** [comment]
I'm in the process of merging & testing this, with a bunch of changes to either improve stuff or integrate it into the latest stuff, e.g. key configuration. Should/can I commit to sondaismith-master?

There's one bug I definitely need to fix - if you hide the main trainer menu, rather than pressing Back until it goes away, you can't get into the Airbrake menu, because it's waiting in a different while loop.

There's also something that annoys me but I can't figure out what the fix is. If you use airbrake on a pedestrian model (rather than a vehicle), it faces 180 degrees away from where it was originally pointing, and where it points again once you stop calling ENTITY::SET_ENTITY_COORDS_NO_OFFSET(). This doesn't happen with vehicles. Any ideas?

**Comment by qaisjp** [comment]
You can't commit to his repository. You'll have to merge his changes to a
branch and then rebase your changes on top, and then merge that into master.

sondaismith, please split pull requests and commits per feature :)

**Comment by gtav-ent** [comment]
Well, he could add me as a collaborator, but it depends what he wants to do with his fork on an ongoing basis. It might not be desirable to have me trash it!

**Comment by qaisjp** [comment]
Eh, fair enough :)

**Comment by sondaismith** [comment]
Which commit are you working off of? The latest one? If I added you as a collaborator would that make it easier for you to add the changes? Would it be better in the future for me to use branches to add new features? I'm still trying to learn how to use GitHub correctly...

**Comment by qaisjp** [comment]
@sondaismith, I apologise if you're already experienced with Git, but here's how I've done it

1. fork `gtav-ent/GTAV-EnhancedNativeTrainer` on GitHub
2. `git clone git@github.com:gtav-ent/GTAV-EnhancedNativeTrainer.git` on my PC
3. `cd GTAV-EnhancedNativeTrainer`
3. `git remote add qais git@github.com:qaisjp/GTAV-EnhancedNativeTrainer.git`

Now whenever I want to make a new feature:

4. `git checkout master` (switch to my copy of the original repo)
5. `git pull` (update my copy)
6. `git branch feature/airbreak` (make a new branch based off the newest gtav-ent version)
7. `git checkout feature/airbreak` (switch to my new branch, when making a new branch this may have already been done)
8. .... do magic stuff....
9. `git push qais` (push my changes to my fork on GitHub)
10. go on github, click "compare & make pull request"

This way, all new features are standalone pull requests that can be independently merged through the GitHub UI.

**Comment by sondaismith** [comment]
@qaisjp OK, thanks for the advice!
@gtav-ent As far as I know the ENTITY::SET_ENTITY_COORDS_NO_OFFSET() method always makes the player model go into the T-Pose and face the screen. I assume it's because it's the default behavior. Maybe if you get it to play a walking animation while the player is moving that would fix the problem?

**Comment by gtav-ent** [comment]
In the interests of getting this available to everyone, this has been merged into the main codebase but airbrake is currently disabled. Feel free to look over it & experiment, I'm a little busy at the mo.

As @qaisjp suggests, lots of small pull requests make life easier, because your new stuff is more likely to keep consistent with everything else that's going on.

**Comment by sondaismith** [comment]
@gtav-ent OK, so it's the issue with hiding the menu and the direction you face while moving? I'll look into those.

**Comment by gtav-ent** [comment]
The menu is the main issue and shouldn't be too hard.

Facing the right way is only a nice-to-have and doesn't block releasing it, it'd just be great if you could figure out a way to avoid it.

I also simplified the airbrake move code, but didn't do the same to the 'through the door' function yet.

The 'never wanted' hotkey is also currently disabled, just because we don't have a decent approach for organising hotkeys yet, and so if we're not careful the keys will get messy. Once the modifiers like Control, Alt etc get added, it will make more sense.

**Comment by qaisjp** [comment]
I suggest that hotkeys are not made for everything, and can be viewed/edited from within the trainer - as a user I'd rather not hit a random key and end up doing something I didn't expect it to do. Especially when I've already bound that key in the controls to do something else.

**Comment by sondaismith** [comment]
OK, I'll leave shortcuts out until that's sorted out then.

**Pull request closed without merging**
