### PR TITLE
Added a clean car option and an extended vehicle mod menu

### PR DESCRIPTION
**Pull request by TSM4278**

### CODE REVIEW

**Comment by qaisjp** [comment]
Please fix your indentation

**Comment by TSM4278** [comment]
I'm sorry, I'm a bit new at this. Can you be more specific?

**Comment by qaisjp** [comment]
It seems that your code uses spaces to indent - the code base uses tabs, if you use VS I suggest you install [this](https://visualstudiogallery.msdn.microsoft.com/dbcb8670-889e-4a54-a226-a48a15e4cace) so that it detects a mixture of tabs/spaces

**Comment by TSM4278** [comment]
As far as I can tell It's all tabs, I used the tabify option in VS13 and edit >> advanced >> view white space shows tabs and not spaces. I Don't know what I'm missing.

**Comment by qaisjp** [comment]
False alarm! I can't read!

Sorry, there's nothing wrong with your indenting :)

**Comment by TSM4278** [comment]
Haha. Ok, I thought I was going crazy. :)

**Comment by gtav-ent** [comment]
Nice work, looks good!

**Pull request merged**
