### PR TITLE
Update teleportation.cpp

### PR DESCRIPTION
**Pull request by fvqu**
Revamped safehouse menu. Decided this way was a lot cleaner and easier to follow. Removed interior teleports for safehouses as I didn't feel they were necessary.

### CODE REVIEW

**Comment by qaisjp** [comment]
I think interior teleports should be kept - what if the doors are locked?

**Comment by gtav-ent** [comment]
Agreed, can we keep them please?

**Comment by fvqu** [comment]
You are the boss after all. My main concern was locked doors, so I decided teleporting players out in front of the safehouse was the best option. I wasn't 100% satisfied with the way I had my last pull laid out so I felt obliged to change it once more.

What if upon selection in this screen opens another submenu for 'Inside' and 'Outside'?

**Comment by gtav-ent** [comment]
I think, and I could be wrong so try it yourself, that in GTAV locked doors only stop you getting in, not out. For example if you change into an NPC whilst in a shop, you can leave but then can't get back in again.

You can have them all together, you could split them into in/out, or if you can figure out how to shoehorn it into the way menus are made, you can add a submenu for just 'Inside' and have all the outside ones as leaf nodes at the higher level if you like. Might be a disproportionate amount of work though.

You could also break the A-Z ordering convention and stick the few important things at the start, as long as there's a good reason for it.

**Comment by qaisjp** [comment]
How about a horizontal selector, similar to how the wanted thing works.
Pressing left/right will select between options "inside" and "outside"

**Pull request closed without merging**
