### PR TITLE
Added a vehicle paint menu

### PR DESCRIPTION
**Pull request by TSM4278**
Works with primary and secondary colors using LSC style color list.
TODO: Still need to add support for wheel color and pearlescent topcoat

### CODE REVIEW

**Comment by gtav-ent** [comment]
Ace - going to put a release out tonight and then I'll look at this tomorrow.

I wondered about creating an RGB colour picker UI - any thoughts on whether it'd fit with this?

**Comment by TSM4278** [comment]
Sounds like a good idea. More options are always a good thing. :)

**Comment by TSM4278** [comment]
Pearlescent working now. Wheel colors work, but do not apply as expected so I have them commented out until I can figure out why.

**Comment by gtav-ent** [comment]
This is great stuff - I just changed it to apply the paint on highlighting a menu option (as per the skins stuff), and it's now released.

**Pull request merged**
