### PR TITLE
WIP weapon attachment and color menu

### PR DESCRIPTION
**Pull request by TSM4278**
Edit: all done and ready to merge.

This functions pretty well as is, but you may want to hold off on merging it in until I can do some more work on it. 

Still needs:
1. DLC weapon mods added (all vanilla weapon mods are in and functioning)
2. A few better checks added (did player switch weapon while in menu?, can this weapon be tinted?)
3. Fix some functional but ugly placeholder code.

I'll be pretty busy for the next few days, but I'll get back to work on it as soon as I can.

### CODE REVIEW

**Comment by TSM4278** [comment]
Added a check to see if weapon was changed while in the attachment menu and did some code cleanup. Still needs DLC weapons added and a better way to check if a weapon is actually tintable.

**Comment by gtav-ent** [comment]
Looks good - I'll get to this on Mon/Tues when I'm at my PC again. I'll probably integrate it into the 'individual weapons' menu so let me know if you're working on it so there's no overlap.

**Comment by TSM4278** [comment]
All done.

**Comment by gtav-ent** [comment]
This is indirectly merged by integrating it into the weapons menu as mentioned. I'm not sure why it hasn't shown up as merged.

**Comment by TSM4278** [comment]
Why didn't you use this? My menu allows you to modify whatever weapon you are holding in your hand. It seems a lot more convenient than scrolling through multiple categories to find the weapon you want to modify. No reason we can't have both ways still in the trainer right?

**Comment by gtav-ent** [comment]
We can do both if you think it makes sense.

A hybrid might be to automatically switch to the weapon whilst in the menu, and to set the menu index to the current weapon, if any. I did think of both of these when integrating, but didn't get chance to do it today.

**Comment by TSM4278** [comment]
I see no reason not to do both, more options are always a good thing. In my personal use atleast, I like just opening a the weapon menu and quickly swapping a suppressor (or whatever) on and off the weapon I'm already holding. 

The individual weapon menu is great for creating complete weapon loadouts, but sometimes I just want to quickly toggle something in a way that the original game should have added as a feature to begin with. Also, this method might go well with a hotkey (when/if more complete support for that is added) so people can push one button and quickly jump to a list of their current weapon options.

**Comment by gtav-ent** [comment]
FYI the approach I described above is in. It'd be easy to add a 'current weapon' menu item at the top level that skips the hierarchy if you think that's beneficial.

Hotkeys and quick access menus are on the radar, although I don't have a totally coherent idea for them yet.

**Comment by TSM4278** [comment]
Well, it's your call. I like it enough that I'll just keep on merging it onto my own personal build either way. Maybe others would find the functionality useful too.

**Pull request closed without merging**
