### PR TITLE
Door control menu

### PR DESCRIPTION
**Pull request by TAWTonic**
Added menu under Vehicle for opening / closing doors, trunk and hood.
Works on planes, ramp is usually TRUNK or BACK LEFT.

TODO: Add key bindings for easy access.

### CODE REVIEW

**Comment by gtav-ent** [comment]
I'll merge this, but I want it to use the generic menu structure rather than the old constantly duplicated code, so it'll have to wait until I get time.

**Comment by TAWTonic** [comment]
Yep, I was digging through your code changes and didn't see much in place for the generic structure or I would of used that to tidy up on code.

C++ is well, not my strongest language due to another game's language that has handicapped me for the past 4-5 years lol.

**Comment by gtav-ent** [comment]
I don't mind doing it but it'll be next week now. The generic mechanism needs a bit more extension to cope with changeable captions for the ON/OFF toggles, but otherwise should suit. The usage by the teleport menu is probably the closest.

**Comment by TAWTonic** [comment]
Saved you a bit of trouble just because I haven't used a proper language in awhile, however have fun with the ON/OFF toggle captions haha.

**Pull request merged**
